eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: monitor-service
server:
  port: 8766
turbine:
  aggregator:
    clusterConfig: default
  app-config: user-service,blog-service
  cluster-name-expression: new String("default")
