spring:
  swagger:
    enable: true
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/mercury?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update