server:
  port: 8762
spring:
  zipkin:
    base-url: http://localhost:9411
spring:
  swagger:
    enable: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mercury?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
