server:
  port: 8769
spring:
  application:
    name: config-service
  cloud:
    profiles:
      active: native
    config:
      server:
        native:
          search-locations: classpath:/shared
